# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_server/protos/messages.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'grpc_server/protos/messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!grpc_server/protos/messages.proto\x12\x08messages\"9\n\x12SendMessageRequest\x12\x12\n\nchannel_id\x18\x01 \x01(\x03\x12\x0f\n\x07message\x18\x02 \x01(\t\"%\n\x13SendMessageResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2b\n\x12SendMessageService\x12L\n\x0bSendMessage\x12\x1c.messages.SendMessageRequest\x1a\x1d.messages.SendMessageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_server.protos.messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDMESSAGEREQUEST']._serialized_start=47
  _globals['_SENDMESSAGEREQUEST']._serialized_end=104
  _globals['_SENDMESSAGERESPONSE']._serialized_start=106
  _globals['_SENDMESSAGERESPONSE']._serialized_end=143
  _globals['_SENDMESSAGESERVICE']._serialized_start=145
  _globals['_SENDMESSAGESERVICE']._serialized_end=243
# @@protoc_insertion_point(module_scope)
